config/routes.rb
Rails.application.routes.draw do
  resources :outfit_clothings, only: [:create]
  get "/outfit_clothings/:outfit_id/new", to: "outfit_clothings#new", as: "new_outfit_clothing"
  
  resources :outfits
  resources :clothings, only: [:show, :index]
  resources :closets, only: [:index, :show, :create]
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  delete '/logout', to: 'sessions#logout', as: "logout"
  get '/login', to: 'sessions#new_login', as: "new_login"
  post '/login', to: 'sessions#login'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/closet.rb
class Closet < ApplicationRecord
    belongs_to :user
    belongs_to :clothing 
end

app/models/clothing.rb
class Clothing < ApplicationRecord
    has_many :closets
    has_many :users, through: :closets
    has_many :outfit_clothings
    has_many :outfits, through: :outfit_clothings
end

app/models/outfit.rb
class Outfit < ApplicationRecord
    belongs_to :user
    has_many :outfit_clothings
    has_many :clothings, through: :outfit_clothings
end

app/models/outfit_clothing.rb
class OutfitClothing < ApplicationRecord
    belongs_to :clothing
    belongs_to :outfit
end

app/models/user.rb
class User < ApplicationRecord
    has_many :closets
    has_many :clothings, through: :closets
    has_many :outfits

    has_one_attached :avatar
    has_secure_password 

    validates :password, length: { minimum: 6 }
    validates :email, presence: true
    validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :logged_in_user
    before_action :logged_in?
    
    def logged_in?
        redirect_to new_login_path unless logged_in_user
    end

    def logged_in_user
        # byebug
        @current_user = User.find_by(id: cookies[:user_id])
    end
end

app/controllers/closets_controller.rb
class ClosetsController < ApplicationController
    def index
        @my_clothes = @current_user.clothings
        #byebug
    end

    def show
        # byebug
        # @closet = Closet.find(params[:id])
    end

    def create
        # byebug
       @add_clothes = Closet.create(closet_params)
       redirect_to closets_path(@current_user)
    end

    private

    def closet_params
        params.permit(:user_id, :clothing_id)
    end

end

app/controllers/clothings_controller.rb
class ClothingsController < ApplicationController
    def index
        if params[:sort] == 'gender'
            @clothings = Clothing.order(:gender) 
            # set instance variable to a list ordered by 'name'
          else
            @clothings = Clothing.all
        end
    end

    def show
        @clothing = Clothing.find(params[:id])
        #byebug
    end

end

app/controllers/outfit_clothings_controller.rb
class OutfitClothingsController < ApplicationController
    def new
        @outfit_clothing = OutfitClothing.new

        @outfit = Outfit.find(params[:outfit_id])
        @clothing = Clothing.all

        @shirts = shirts
        @pants = pants
        @accessories = accessories
        @shoes = shoes
    end

    def create
        # @outfit_clothing = OutfitClothing.find(params[:id])

        # @outfit = Outfit.find(params[:outfit_id])

        params[:outfit_clothing].each do |clothing_hash| 
           OutfitClothing.create(clothing_id: clothing_hash[:clothing_id], outfit_id: params[:outfit_id])
        end 
        
    
        redirect_to outfit_path(params[:outfit_id])
    end

    private

    # def outfit_clothing_params
    #     params.require(:outfit_clothing).permit(:outfit_id, :clothing_id)
    # end

    def shirts
        Clothing.select do |clothing| 
            clothing.category == "Shirt"
        end
    end

    def pants
        Clothing.select do |clothing| 
            clothing.category == "Pant"
        end
    end

    def accessories
        Clothing.select do |clothing| 
            clothing.category == "Accessory"
        end
    end

    def shoes
        Clothing.select do |clothing| 
            clothing.category == "Shoe"
        end
    end
end

app/controllers/outfits_controller.rb
class OutfitsController < ApplicationController
    def index
        @outfits = Outfit.all
    end

    def show
        @outfit = Outfit.find(params[:id])
        #byebug
    end

    def new
        @outfit = Outfit.new
    end 

    def create
        @outfit = Outfit.create(outfit_params)
        
        redirect_to outfit_path(@outfit.id)
    end

    def edit
        @outfit = Outfit.find(params[:id])
    end

    def update
        @outfit = Outfit.find(params[:id])
        #byebug
        @outfit.update(outfit_params)

        redirect_to outfit_path(@outfit)
    end

    def destroy 
        @outfit = Outfit.find(params[:id])

        @outfit.delete

        redirect_to outfits_path
    end


    private

    def outfit_params
        params.require(:outfit).permit(:name, :user_id)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    skip_before_action :logged_in?, only: [:new_login, :login]

    def new_login

    end

    def login
        # find a user based on email
        user = User.find_by(email: params[:session][:email])
        # byebug
        #validate that user based on their password
        if user && user.authenticate(params[:session][:password])
        #set a cookie 
            cookies[:user_id] = user.id
            redirect_to user_path(user)
        else
            flash[:error] = "Password or Email is incorrect"
            redirect_to new_login_path
        end
    end

    def logout
        cookies.delete(:user_id)

        redirect_to new_login_path
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    skip_before_action :logged_in?, only: [:index, :new, :create]

    
    def index
        @users = User.all
    end

    def show
        @user = User.find(params[:id])
        # byebug
        if @current_user == @user 
            render :show
          else  
            flash.now[:messages] = "You can only see your own profile"
            redirect_to users_path
        end
    end

    def new
        @user = User.new
    end

    def create
        @user = User.create(user_params)
        # byebug
        if @user.valid?
            cookies[:user_id] = @user.id
            redirect_to @user
          else
            flash[:messages] = @user.errors.full_messages
            redirect_to new_user_path
        end 
    end

    def destroy
        @user = User.find(params[:id])

        @user.delete

        redirect_to users_path
    end

    def edit
        @user = User.find(params[:id])
    end

    def update
        @user = User.find(params[:id])

        @user.update(user_params)

        redirect_to user_path(@user)
    end

    private 

    def user_params
        params.require(:user).permit(:name, :avatar, :gender, :email, :password)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/closets_helper.rb
module ClosetsHelper
end

app/helpers/clothings_helper.rb
module ClothingsHelper
end

app/helpers/outfit_clothings_helper.rb
module OutfitClothingsHelper
end

app/helpers/outfits_helper.rb
module OutfitsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/closets/index.html.erb
<div class="closet-container">
    <div class="closet-parent">
        <div class="div6">
            <ul id="navbar">
                <li><a><%= link_to "Go Shopping", clothings_path %></a></li>
                <li><a><%= link_to "My Profile", user_path(@current_user) %></a></li>
            </ul>
        </div>


        <div class="div7">
            <h1 class="closet">My Closet</h1>
            <hr>
        </div>


        <div class="div8"> 
                <% @my_clothes.each do |clothing| %>
                <div class="closet-card">
                    <%= link_to clothing.name, clothing_path(clothing) %>
                </div>
                <% end %>
        </div>
    </div>
</div>
<%# link_to "Create a Fit!", new_outfit_clothing_path(@outfit) %>

app/views/clothings/index.html.erb
<div class="container">
  <div class="parent">
    <div class="div1">
      <ul id="navbar">
        <li><a><%= link_to "My Closet", closets_path %></a></li>
        <li><a><%= link_to "My Profile", user_path(@current_user) %></a></li>
      </ul>
    </div>

    <div class="div7">
        <h1 class="closet">All Clothes</h1>
        <hr>
    </div>

    <div class="div8">
        <% @clothings.each do |clothing|%>
            <div class="clothing-card">
              <%= image_tag clothing.img_url %>
              <ul><a><%= link_to clothing.name, clothing_path(clothing)%><a></ul>
              </div>
          <% end %>
    </div>  

<%# link_to "See the Outfits by Gender", clothings_path(:sort =>'gender') %>

app/views/clothings/show.html.erb
<div class="container"> 
    <div class="parent">
        <div class="div1">
            <ul id="navbar">
                <li><a><%= link_to "My Closet", closets_path(@current_user) %></a></li>
                <li><a><%= link_to "Go Shopping", clothings_path %></a></li>
            </ul>
        </div>


        <div class="div7">
            <h2 class="closet"><%= @clothing.name%></h2>
            <hr>
        </div>

<div class="div3">
    <div class="card">
        <%= image_tag @clothing.img_url %>
    </div>
</div>

<div class="div4">
    <div class="card">
        <h3><%= @clothing.description%></h3>
        <hr>
        <h3><%= @clothing.category%></h3>
        <hr>
        <h3><%= @clothing.gender %></h3>
    </div>
</div>

<div class="div5">
<%# if @current_user.logged_in? %>
<% if @current_user.clothings.find_by(id: @clothing.id)  %>
    <strong><p>You Own This!</p></strong>
    <% else %>
    <%# have a form that sends back user_id & clothing_id %>
    <%# sends to coleset controler and create  %>
    <%= form_tag '/closets' do %>
        <%= hidden_field_tag  :user_id, @current_user.id %>
        <%= hidden_field_tag :clothing_id, @clothing.id %>
        <%= submit_tag "Add to Closet" %>
    <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FitForYou</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%# javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class='banner-image'>
      <div class='banner-overlay'>
        <%= image_tag 'logo.png', class: 'ffy_logo' %>
      </div>
    </div>
  <nav>
    <div class='right'>
      <% if @current_user %>
        <%= link_to "Welcome #{@current_user.name}!", @current_user  %>
        <%= button_to "Logout", logout_path, method: :delete  %>
      <% else %>
        <%= link_to 'Sign up', new_user_path %> <a>|<a>
        <%= link_to 'Login', new_login_path %>
      <% end %>

    </div>
  </nav>
    
    <%= yield %>
  </body>
</html>

app/views/outfit_clothings/new.html.erb
<div class="container">
  <div class="parent">
    <div class="div1">
        <ul id="navbar">
            <li><a><%= link_to "Go Back", outfit_path(@outfit) %></li></a>
        </ul>
    </div>

    <div class="div7">
        <h1 class="closet">Pick Your Piece(s)</h1>
        <hr>
    </div>


<div class="div8">
    <%= form_tag "/outfit_clothings" do %>
    <div class="welcome-card">
        <%= hidden_field_tag :outfit_id, @outfit.id %>
        <strong><p><%= label_tag "Choose a Top: " %>
        <%= collection_select("outfit_clothing[]", :clothing_id, @shirts, :id, :name, { include_blank: "--Tops--" }, { :class => "input-xlarge" } ) %></p>
        <strong><p><%= label_tag "Choose a Bottom: " %>
        <%= collection_select("outfit_clothing[]", :clothing_id, @pants, :id, :name, { include_blank: "--Bottoms--" }, { :class => "input-xlarge" } ) %></p>
        <strong><p><%= label_tag "Choose an Accessory: " %>
        <%= collection_select("outfit_clothing[]", :clothing_id, @accessories, :id, :name, { include_blank: "--Accessories--" }, { :class => "input-xlarge" } ) %></p>
        <strong><p><%= label_tag "Choose a Shoe: " %>
        <%= collection_select("outfit_clothing[]", :clothing_id, @shoes, :id, :name, { include_blank: "--Shoes--" }, { :class => "input-xlarge" } ) %></p>
        <%= submit_tag "Add to Outfit" %>
    <% end %>
    </div>
</div>

app/views/outfits/edit.html.erb
<h1>Edit your fit</h1>

<%= form_for @outfit do |f| %>
    <p><strong><%= f.label "Name:" %>
    <%= f.text_field :name %></p>
    <p><strong><%= f.label "Choose a Top: " %>
    <%= f.collection_select :clothing_ids, @shirts, :id, :name %></p>
    <p><strong><%= f.label "Choose a Bottom: " %>
    <%= f.collection_select :clothing_ids, @pants, :id, :name %></p>
    <p><strong><%= f.label "Choose an Accessory: " %>
    <%= f.collection_select :clothing_ids, @accessories, :id, :name %></p>
    <p><strong><%= f.label "Choose a Shoe: " %>
    <%= f.collection_select :clothing_ids, @shoes, :id, :name %></p>
    <%= f.submit %>
<% end %>

app/views/outfits/index.html.erb
<h1>Outfit Index Page</h1>

<% @outfits.each do |outfit|%>
<li><%= link_to outfit.name, outfit_path(outfit)%></li>
<% end %>

<p><%= link_to "Create a New Fit", new_outfit_path %>
<%# link_to "See the Outfits by Category", outfits_path(:sort =>'Category') %>

app/views/outfits/new.html.erb
<div class="container">
  <div class="parent">
    <div class="div1">
      <ul id="navbar">
        <li><a><%= link_to "Go Shopping", clothings_path %></a></li>
        <li><a><%= link_to "Go Back", user_path(@current_user) %></a></li>
      </ul>
    </div>

    <div class="div7">
        <h1 class="closet">Let's Put Together A New Fit</h1>
        <hr>
    </div>

    <div class="div8">
        <div class="closet-card">
            <%= form_for @outfit do |f| %>
                <%= f.hidden_field :user_id, value: @current_user.id %></p>
                <p><strong><%= f.label "Name:" %>
                <%= f.text_field :name %></p>
                <%= f.submit "Save"%>
            <% end %>
        </div>
    </div>  
</div>
<%# link_to "Go Back", outfits_path %>

app/views/outfits/show.html.erb
<div class="container">
  <div class="parent">
    <div class="div1">
        <ul id="navbar">
            <li><a><%= link_to "My Profile", user_path(@current_user) %></a></li>
            <li><a><%= link_to "My Closet", closets_path %></a></li>
            <li><a><%= link_to "Add Clothing to this Fit", new_outfit_clothing_path(@outfit.id) %></a></li>
        </ul>
    </div>


    <div class="div7">
        <h1 class="closet">Outfit <%= @outfit.name %></h1>
        <hr>
    </div>

<div class="div8">
      <div class="outfit-card">
<% @outfit.outfit_clothings.map do |outfit| %>
    <p><%= outfit.clothing.category %> : <%= image_tag outfit.clothing.img_url %></p>
<% end %>
</div>
    </div>


<div class="div5">
      <a class="delete"><%= button_to "Delete This Fit?", user_path(@current_user), method: :delete %></a>
    </div>
</div>

app/views/users/edit.html.erb
<div class="container">
  <div class="parent">
    <div class="div1">
      <ul id="navbar"> 
        <li><a><%= link_to "Go Back", user_path(@current_user) %></a></li>
      </ul>
    </div>
    
    <div class="div7">
        <h1 class="closet"> Edit Your Profile</h1>
    </div>

    <div class="div8">
        <div class="closet-card">
            <%= form_for @user do |f|%>
                <%= f.label "Name: "%>
                <%= f.text_field :name%>
                <br>
                <%= f.label "Gender: "%>
                <%= f.text_field :gender %>
                <br>
                <%= f.label "Profile Pic: "%>
                <%= f.file_field :avatar%>
                <br>
                <%= f.label "Email Address: "%>
                <%= f.text_field :email%>
                <br>
                <br>
                <%= f.submit "Save" %>
            <%end%>
        </div>
    </div>  
</div>

app/views/users/index.html.erb
<head>
    <title>All Users</title>
</head>

<% @users.each do |user|%>
<li><%= link_to user.name, user_path(user)%>
<%end%>

app/views/users/new.html.erb
<div class="welcome-card">
<div class="welcome"> 
<h1>Create an Account</h1>
</div>
<div class='form-input'>
<%= form_for @user do |f|%>
<%= f.label "Name: "%>
<%= f.text_field :name%>
</div>

<div class='form-input'>
<%= f.label "Gender: "%>
<%= f.text_field :gender %>
</div>

<div class='form-input'>
<%= f.label "Profile Pic: "%>
<%= f.file_field :avatar%>
<div>

<div class='form-input'>
<%= f.label "Email Address: "%>
<%= f.text_field :email%>
</div>

<div class='form-input'>
<%= f.label "Password: "%>
<%= f.password_field :password%>
</div>

<%= f.submit "Done" %>
<%end%>

<% if flash[:messages] %>
    <% flash[:messages].each do |message|%>
      <p style="color: red;"><%= message %>
    <% end %>
<% end %>

</div>

app/views/users/show.html.erb
<div class="container">
  <div class="parent">
    <div class="div1">
      <ul id="navbar">
        <li><a><%= link_to "My Closet", closets_path %></a></li>
        <li><a><%= link_to "Go Shopping", clothings_path %></a></li>
        <li><a><%= link_to "Create a New Fit", new_outfit_path %></a></li>
        <li><a><%= link_to "Edit Profile", edit_user_path %></a></li>
      </ul>
    </div>
  
    <div class="div5">
      <a class="delete"><%= button_to "Delete Your Profile?", user_path(@user), method: :delete %></a>
    </div>

    <div class="div2">
      <h1 class="profile">My Profile</h1>
      <hr>
      <% if flash[:messages]%>
      <%= flash[:messages] %>
      <% end %>
    </div>
    <div class="div3">
      <div class="card">
        <% if @user.avatar.attached? %>
          <img src="<%= (url_for(@user.avatar)) %>" alt="<%= @user.name %>" width="500" height="400">
        <% end %>
        <hr>
        <a><%= @user.name%></a>
        </div>
    </div>

    <div class="div4">
      <div class="card">
        <h3 class="outfit">My Outfits</h3>
          <% @user.outfits.each do |outfit| %>
          <p><%= link_to outfit.name, outfit_path(outfit) %></p>
          <hr>
        <% end %>
      </div>
    </div>
  </div>
</div>